### ISSUE TITLE
Looping on phone number 

### ISSUE THREAD

**Issue by cry8wolf9** [Brismuth-Apps-LLC/bulk-texter-lite#180]
**Describe the bug**
Looping on putting in phone number does not get to message stage. First one sometimes sends correctly
**URL**
Voice.google.com

**Expected behavior**
For it to send the message

**Comment by brismuth** [comment]
Is this still happening for you?

See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message:
> **Extension is looping on a single number and failing with an error message**
This is usually caused by Google Voice rolling out website changes in phases. Check if there are any [open issues](https://github.com/brismuth/google-voice-bulk-texter/issues) reporting the issue already, and if there are, feel free to subscribe to them or comment on them. If there are no issues already reported, open a new one by following the instructions [below](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#support).

**Comment by cry8wolf9** [comment]
Yeah, I haven't been able to use it since I posted that. 
I've tried cleaning the cache and everything associated with it but no luck

**Comment by brismuth** [comment]
Okay, I’m not able to reproduce the issue right now so I’m not able to fix it, but if you want to take a look at the source code, the fix will likely be here or on one of the lines next to it:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/src/contentScripts/main.js#L9
