### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Muppetmama** [Brismuth-Apps-LLC/bulk-texter-lite#217]
I get an error message "switch to messages tab failed to start"
Katherine Burke
muppetmama02@gmail.com

**Comment by brismuth** [comment]
This item from the top of the Support page will resolve your issue:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/support.md#general-tips

> Before proceeding with this guide, make sure that you are running the latest version of Bulk Texter Lite by following the [update guide](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/blob/main/README.md#update-it).

Google made some changes that broke Bulk Texter Lite, but the updates needed for Bulk Texter Lite were released last week. I recommend using Bulk Texter Lite on Firefox instead of Chrome, so it will stay up to date automatically.
