### ISSUE TITLE
Attempting to send message. Voice Texter Lite will not send

### ISSUE THREAD

**Issue by CoachStorm** [Brismuth-Apps-LLC/bulk-texter-lite#220]
Hello GitHub Team,
I have been using Google Voice Bulk Texter. It may be the same, but since using bulk-texter-lite my messages have not been going out. I deleted the entire file and re-installed. I have limited the number of people I send the information to, Less than 5 people. I've also just done a test run of bulk Lite to my own phone. Still did not send out. 

I try regular Google Voice and it does send and receive messages and also in groups, 2-5 people in the same text, but then everyone sees everyone else's answers. So, not what I'd like to do.  The error message I get is attached to this email. I made screenshots.  I'm not tech savvy at the moment, I am learning a lot, so bear with me if you ask a question and I sound clueless. It's probably because I am. Thank you for your help.--Storm
[Google Voice Bulk Texter Lite (2).pdf](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/files/10725589/Google.Voice.Bulk.Texter.Lite.2.pdf)
[Google Voice Bulk Texter Lite (1).pdf](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/files/10725590/Google.Voice.Bulk.Texter.Lite.1.pdf)
[Google Voice Bulk Texter Lite.pdf](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/files/10725591/Google.Voice.Bulk.Texter.Lite.pdf)

**Comment by brismuth** [comment]
No worries Coach Storm, the good news is it's an easy fix. 

You just need to update to the latest version following this guide - the error you're seeing was resolved a couple months ago:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite#update-it

We also recommend using Bulk Texter Lite on Firefox instead of Chrome, as it will automatically stay up to date on the latest version. 

You may also want to check out Bulk Texter Pro, if you haven't. https://www.bulktexterpro.com
