### ISSUE TITLE
SMS Double sending at times

### ISSUE THREAD

**Issue by setvalsantos** [Brismuth-Apps-LLC/bulk-texter-lite#232]
Started using Bulk Texter Lite last week for our Workspace account.

Some of our users experience double-sending. Low percentage like 1 of 50. But happened to multiple people.

What can cause this? Users claim they do not have multiple entries of those numbers that are duplicated.

**Comment by brismuth** [comment]
Hi @setvalsantos.

Bulk Texter Lite will retry any of the steps in the sending process until it attempts to click the "Send" button. Once it attempts to click the "Send" button even once, it will not retry the same text message again, even if it thinks it failed to send. It will display an error message instead of retrying after that point, if it thinks it failed. 

Here are some things I'd recommend checking:
* That there are no duplicates in the contact list. I know you mentioned that already, but that does happen sometimes.
* That users aren't clicking on or interacting with the Google Voice page while Bulk Texter Lite is sending.
* That users are fully up to date on the latest version of Bulk Texter Lite.

Also, Bulk Texter Pro has additional checks and features to catch issues like this before they happen, and it also tracks all send history, making troubleshooting much easier and more effective. It's very popular with schools – not sure if that's your use case or not.
https://www.bulktexterpro.com/
