### ISSUE TITLE
FillNumberInput Failed

### ISSUE THREAD

**Issue by shanannana** [Brismuth-Apps-LLC/bulk-texter-lite#237]
I have been using bulk texter lite on Microsoft Edge ever since the chrome extension stopped working in our building (about a year ago).  I use it to notify families that their children are absent from school so it is a vital took for my job.  It was working fine last week but today, it would show "No Contact Found" and then have the fail popup (see below).  I tried to remove and re-add the file.  I restarted my computer but no luck. I also tried again on chrome and I had the same issues.  I really hope this is resolved.  

![Screenshot 2023-12-19 102406](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/154350494/7f1b5fc2-7316-4666-a8e6-00c879f9ea60)

![Screenshot 2023-12-19 102232](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/154350494/caacddae-f0e7-4cbd-9a94-6da877ece177)

**Comment by ZRScott** [comment]
Having the same issue on chrome.

**Comment by brismuth** [comment]
The fix is now live in Bulk Texter Lite v3.0.2.

Please note that due to Google's recent changes, Google Voice does not currently support texting while in the background – you'll need to be clicked into the Google Voice tab for it to send.

v3.0.2 is released to the Firefox web store, and is still pending approval in the Edge web store.

You can follow the instructions here to update to the latest version manually:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/tree/main?tab=readme-ov-file#update-it

**Comment by brismuth** [comment]
@shanannana @ZRScott background sending functionality is restored in Bulk Texter Lite v3.0.3!

v3.0.3 is released to the Firefox web store, and is still pending approval in the Edge web store.

You can follow the instructions here to update to the latest version manually:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/tree/main?tab=readme-ov-file#update-it
