### ISSUE TITLE
automatically stops when texting

### ISSUE THREAD

**Issue by AlxndrCtamn** [Brismuth-Apps-LLC/bulk-texter-lite#240]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
January 20, 2024

**Describe the bug**
In Bluktexter Lite we currently have an issue with Google Voice, as it automatically stops when texting.

**Screenshots**

**Comment by brismuth** [comment]
That's not a lot of detail to go on, is there any more information you can provide?

Are there any error messages being shown when it happens? Are there any error messages shown on chrome://extensions? Does it send any messages at all? Does it stop after a while, or immediately? Or after the first text?

**Comment by AlxndrCtamn** [comment]
There are no error messages shown in Chrome/Google. But after sending a text for about 1 hour, they stop.

**Comment by olafralph16** [comment]
Hi! I've been encountering this issue for a week now. After clicking "send," the messages don't fully send to all numbers. It randomly stops at certain numbers, failing to complete the send out to all the listed numbers.

**Comment by brismuth** [comment]
After investigating more, I found an edge case where sometimes the last step in the sending process (clicking the send button) would sometimes silently fail and get stuck, stopping the process.

I've just released Bulk Texter Lite v3.0.4, which should fix the issue, making it so that if there are any errors they are clearly shown. Firefox and Edge are still reviewing the change, but it's available now for manual installation.

You can see update instructions here:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite?tab=readme-ov-file#update-it
