### ISSUE TITLE
v3.0.8: "fillNumberInput" failed.

### ISSUE THREAD

**Issue by Geremia** [Brismuth-Apps-LLC/bulk-texter-lite#244]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
Bulk Texter Lite was working, then this issue cropped up.
I was able to send many texts.
It's not a rate-limiting issue, as I'm still able to successfully send texts manually.
I'm using FireFox 115.8.0esr (64-bit) on Linux.

**Describe the bug**
Regression of #236 
```
Bulk Texter Lite v3.0.8:
Text failed. "fillNumberInput" failed.

You can find support resources by opening the Bulk Texter Lite popup and clicking "Get Help" at the bottom.

When you click "ok" the page will refresh.
```
Clicking to refresh, Bulk Texter Lite starts working again.

**Screenshots**
<img src="https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/4298614/c952d885-bec8-42cb-bf58-18eff29e850e" width=63%>

**Comment by brismuth** [comment]
@Geremia #236 was an issue where Google Voice had changed their web interface code, which required an update to Bulk Texter Lite in order to work with their new code.

Your description here sounds like it's more of a transient issue, where sometimes the `fillNumberInput` error occurs, but a simple page refresh allows it to continue sending – is that right? How often is that happening? Is it every time you try to send a batch of texts?

**Comment by Geremia** [comment]
@brismuth  Yes, it's transient. I haven't gotten it recently, though I did about 1½ weeks ago.

**Comment by brismuth** [comment]
Got it, thanks for the additional detail. I'll keep this in mind, and if I get more reports or if you find consistent steps to reproduce, I'll dig in further and see if I can fix whatever is happening.

**Comment by ElaineAlbright** [comment]
STOP………
No more of your F…ng time wasting emails!

**Comment by brismuth** [comment]
@ElaineAlbright, just so you know, you are posting on a public community forum. If you're receiving email notifications from this forum, it's because you signed up for email notifications at some point. I don't have any access to change your personal notification preferences on Github – that's something you'll need to do yourself. Every email you receive from Github has instructions at the bottom of the email for how to unsubscribe.

**Comment by irishknots** [comment]
Not Necro threading here - Just ran into this same issue and it is persistent. 

V 3.1.3

![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/53129769/d9f6e2a9-229c-4779-8f0f-bc57bfea3754)

**Comment by irishknots** [comment]
Resolved my own issue - its a google voice problem. Have to ensure account and number are all active.
