### ISSUE TITLE
Message sending issue

### ISSUE THREAD

**Issue by Lmvellous2** [Brismuth-Apps-LLC/bulk-texter-lite#253]
Good day i just purchase the software of which i used to send messages and is not going i wish  to know if the error is from  the software i purchased or if there is possible way to fix this issues. earlier stage i thought is due to free version but still after i bought the paid version is still the same.Kindly help me to rectify this. Thanks the affected mail is lakindariana883@gmail.com and google voice number (646) 770-0391‬

**Comment by brismuth** [comment]
Hi @Lmvellous2, are you getting any error messages? If so, can you share them?

If any texts fail to send via Bulk Texter Lite, you'll want to try sending the same text manually, without Bulk Texter Lite, and see if that works. If that doesn't work either, then it's likely that Google Voice doesn't like the text message content or they are rate limiting your account – either way, that's an issue on the Google Voice side, rather than the Bulk Texter Lite side.
