### ISSUE TITLE
Add support for additional arguments / parameters

### ISSUE THREAD

**Issue by andyxmai** [Brismuth-Apps-LLC/bulk-texter-lite#49]
**Is your feature request related to a problem? Please describe.**
I usually need to send one more argument in addition to the name. Be it an address or phone number.

**Describe the solution you'd like**
An optional second argument in additional to {{name}}

**Describe alternatives you've considered**
Skip the name and use {{name}} for my second argument. This works, but it's less personalized.

**Comment by brismuth** [comment]
Thanks for the feature request. I’m also open to pull requests if anyone else is interested in contributing to the project.

**Comment by EdWood110** [comment]
I totally like the idea to have more arguments available as well! Great Idea!

**Comment by donnyPD** [comment]
Following this thread as I am also interested in additional fields. Specially address and email.
Thank you

**Comment by wanoknzjj** [comment]
I did as written on your readme.md but NOTHING WORKED. my voice still sends the message in group after I have inputted the contacts one after another, then it automatically creates a group for those contacts and send message. and thats not what I think the extension should be all about.. or maybe it doesn't even work at all. the way it popped out on your demo, it doesn't pop out or even show anything when I'm on the voice page. frustrating you know!

**Comment by brismuth** [comment]
@wanoknzjj 
1) You’re commenting on someone else’s open issue about something completely unrelated. Please avoid that in the future if possible. 
2) It sounds like you’re just entering all your contacts into google voice instead of using the extension at all. Click on the Google Voice Bulk Texter extension icon up in your browser’s extension bar (assuming you’ve installed it correctly) - that will open the popup. If what you’re seeing doesn’t look like the demo screenshot then you’re not using the extension at all. 

If you’re still having issues after following these instructions, please open a separate issue thread. 

Thanks!

**Comment by brismuth** [comment]
People who would like this issue prioritized can fund it here:
https://issuehunt.io/r/brismuth/google-voice-bulk-texter/issues/49

**Comment by alzamorm** [comment]
It will be very helpful if we are allowed to add more arguments. Any update if this feature is available?

**Comment by rrobert45** [comment]
Any update on more arguments?

**Comment by brismuth** [comment]
Hey folks - I have an exciting announcement!

I just launched Bulk Texter Pro over at https://www.bulktexterpro.com/ - it supports CSV upload with multiple columns, as well as scheduling messages in advance and message previewing - it's pretty slick. I'd love if you could check it out and drop any feedback you have here.
